import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generate a clinical prescription PDF that looks like a real Indian clinic/hospital document.
 * Includes: Doctor letterhead with Rx symbol, patient demographics box,
 * SOAP notes, prescription table with Rx header, patient instructions, and signature line.
 */
export function generatePatientPDF({ patient, doctor = {}, consultations = [], includeAllConsultations = false }) {
  const doc = new jsPDF();
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const m = 14; // margin
  const cw = pw - 2 * m; // content width

  // Colors (clinical blue/dark theme)
  const navy = [15, 23, 42];
  const blue = [37, 99, 235];
  const gray = [71, 85, 105];
  const lightGray = [148, 163, 184];
  const lineColor = [203, 213, 225];
  const rxGreen = [22, 163, 74];
  const bgLight = [248, 250, 252];

  const toRender = includeAllConsultations ? consultations : consultations.slice(0, 1);
  const now = new Date();
  const dateNow = now.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

  // ═══════════════════════════════════════════════
  // Helper: add letterhead to every page
  // ═══════════════════════════════════════════════
  const addLetterhead = () => {
    const clinicName = doctor.clinicHospitalName || 'Medical Clinic';
    const drName = doctor.fullName ? `Dr. ${doctor.fullName}` : 'Doctor';
    const quals = [doctor.qualification, doctor.specialization].filter(Boolean).join(', ');
    const regNo = doctor.medicalRegNumber ? `Reg. No: ${doctor.medicalRegNumber}` : '';
    const addr = doctor.clinicAddress || {};
    const addressLine = [addr.district, addr.state, addr.pin ? `- ${addr.pin}` : ''].filter(Boolean).join(', ');
    const phone = doctor.phone || '';
    const email = doctor.email || '';

    // Top border line
    doc.setDrawColor(...blue);
    doc.setLineWidth(1.5);
    doc.line(m, 10, pw - m, 10);
    doc.setLineWidth(0.3);
    doc.line(m, 11.5, pw - m, 11.5);

    // Clinic name
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...navy);
    doc.text(clinicName, pw / 2, 19, { align: 'center' });

    // Doctor name + qualifications
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...blue);
    doc.text(drName, pw / 2, 26, { align: 'center' });

    if (quals) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...gray);
      doc.text(quals, pw / 2, 31, { align: 'center' });
    }

    // Contact info row
    let infoY = 36;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...lightGray);
    const infoParts = [regNo, addressLine, phone, email].filter(Boolean);
    if (infoParts.length > 0) {
      doc.text(infoParts.join('  |  '), pw / 2, infoY, { align: 'center' });
      infoY += 5;
    }

    // Bottom border
    doc.setDrawColor(...blue);
    doc.setLineWidth(0.5);
    doc.line(m, infoY, pw - m, infoY);

    return infoY + 4;
  };

  // ═══════════════════════════════════════════════
  // Helper: add footer to every page
  // ═══════════════════════════════════════════════
  const addFooter = (pageNum, totalPages) => {
    doc.setDrawColor(...lineColor);
    doc.setLineWidth(0.3);
    doc.line(m, ph - 20, pw - m, ph - 20);

    doc.setFontSize(7);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...lightGray);
    doc.text('This prescription is computer-generated and is valid without signature.', m, ph - 15);
    doc.text('Not a substitute for professional medical advice.', m, ph - 11);

    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by SwasthyaMitra | ${dateNow}`, pw - m, ph - 15, { align: 'right' });
    doc.text(`Page ${pageNum} of ${totalPages}`, pw - m, ph - 11, { align: 'right' });
  };

  // ═══════════════════════════════════════════════
  // PAGE 1: Letterhead + Patient Info + Consultation
  // ═══════════════════════════════════════════════
  let y = addLetterhead();

  // ─── Patient Information Box ───
  // Light background box
  doc.setFillColor(...bgLight);
  doc.setDrawColor(...lineColor);
  doc.setLineWidth(0.3);
  doc.roundedRect(m, y, cw, 32, 2, 2, 'FD');

  y += 5;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...navy);
  doc.text('PATIENT DETAILS', m + 4, y);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...gray);
  doc.text(`Date: ${dateNow}`, pw - m - 4, y, { align: 'right' });

  y += 6;
  const col1 = m + 4;
  const col2 = m + cw * 0.35;
  const col3 = m + cw * 0.65;

  // Row 1
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...navy);
  doc.setFontSize(10);
  doc.text(patient.name || 'Patient', col1, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...gray);
  doc.text(`Age: ${patient.age || '--'} yrs`, col2, y);
  doc.text(`Gender: ${patient.gender || '--'}`, col3, y);

  y += 5.5;
  // Row 2
  doc.text(`Phone: ${patient.phone || '--'}`, col1, y);
  doc.text(`Blood Group: ${patient.bloodGroup || '--'}`, col2, y);
  const langLabel = patient.language ? patient.language.charAt(0).toUpperCase() + patient.language.slice(1) : '--';
  doc.text(`Language: ${langLabel}`, col3, y);

  y += 5.5;
  // Row 3 - Medical
  doc.text(`Allergies: ${patient.allergies || 'None'}`, col1, y);
  doc.text(`Conditions: ${patient.conditions || 'None'}`, col2, y);

  y += 5.5;
  doc.text(`Current Medications: ${patient.medications || 'None'}`, col1, y);

  y = y + 8; // after patient box

  // ─── Consultations ───
  if (toRender.length === 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...lightGray);
    doc.text('No consultation records available.', m, y + 5);
  }

  toRender.forEach((consult, idx) => {
    if (y > 220) { doc.addPage(); y = addLetterhead(); }

    // Consultation date header
    const cDate = new Date(consult.date);
    const cDateStr = cDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
    const cTimeStr = cDate.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

    if (idx > 0) {
      doc.setDrawColor(...lineColor);
      doc.setLineWidth(0.3);
      doc.line(m, y, pw - m, y);
      y += 5;
    }

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...blue);
    doc.text(`Consultation  —  ${cDateStr}  ${cTimeStr}`, m, y);
    y += 7;

    // ─── SOAP Notes ───
    const soapSections = [
      { label: 'Chief Complaint / Subjective', content: consult.soap_note?.subjective },
      { label: 'Examination / Objective', content: consult.soap_note?.objective },
      { label: 'Diagnosis / Assessment', content: consult.soap_note?.assessment },
      { label: 'Treatment Plan', content: consult.soap_note?.plan },
    ];

    soapSections.forEach(({ label, content }) => {
      if (!content) return;
      if (y > 245) { doc.addPage(); y = addLetterhead(); }

      // Label
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...navy);
      doc.text(label, m, y);
      y += 4.5;

      // Content
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...gray);
      const lines = doc.splitTextToSize(content, cw);
      doc.text(lines, m + 2, y);
      y += lines.length * 4.2 + 4;
    });

    // ─── Prescription (Rx) ───
    if (consult.medications?.length > 0) {
      if (y > 220) { doc.addPage(); y = addLetterhead(); }

      // Rx symbol
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...rxGreen);
      doc.text('Rx', m, y + 1);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...navy);
      doc.text('Prescription', m + 14, y);
      y += 3;

      const medRows = consult.medications.map((med, i) => [
        String(i + 1),
        med.name || '--',
        med.dosage || '--',
        med.frequency || '--',
        med.duration || '--',
      ]);

      autoTable(doc, {
        startY: y,
        head: [['#', 'Medication', 'Dosage', 'Frequency', 'Duration']],
        body: medRows,
        theme: 'striped',
        styles: {
          fontSize: 9,
          cellPadding: 3,
          textColor: navy,
          lineColor: lineColor,
          lineWidth: 0.2,
        },
        headStyles: {
          fillColor: [37, 99, 235],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
          fontSize: 8.5,
        },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        columnStyles: {
          0: { cellWidth: 10, halign: 'center' },
          1: { fontStyle: 'bold', cellWidth: 50 },
          2: { cellWidth: 30 },
          3: { cellWidth: 40 },
          4: { cellWidth: 30 },
        },
        margin: { left: m, right: m },
      });

      y = doc.lastAutoTable.finalY + 6;
    }

    // ─── Patient Instructions / Advice ───
    const instructions = consult.patient_instructions_translated || consult.patient_instructions;
    if (instructions) {
      if (y > 235) { doc.addPage(); y = addLetterhead(); }

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...navy);
      doc.text('Advice / Patient Instructions', m, y);
      y += 5;

      // Instructions box with left border
      doc.setDrawColor(...rxGreen);
      doc.setLineWidth(1);
      const instrLines = doc.splitTextToSize(instructions, cw - 8);
      const instrHeight = instrLines.length * 4.2 + 4;
      doc.line(m, y - 2, m, y + instrHeight);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...gray);
      doc.text(instrLines, m + 4, y);
      y += instrHeight + 4;
    }

    // ─── Follow-up / Signature area ───
    if (y > 245) { doc.addPage(); y = addLetterhead(); }

    y += 8;

    // Signature line on right
    const sigX = pw - m - 60;
    doc.setDrawColor(...navy);
    doc.setLineWidth(0.3);
    doc.line(sigX, y, pw - m, y);
    y += 4;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...gray);
    doc.text(doctor.fullName ? `Dr. ${doctor.fullName}` : 'Doctor\'s Signature', sigX + 30, y, { align: 'center' });
    y += 3.5;
    if (doctor.qualification) {
      doc.setFontSize(7);
      doc.text(doctor.qualification, sigX + 30, y, { align: 'center' });
      y += 3.5;
    }
    if (doctor.medicalRegNumber) {
      doc.setFontSize(7);
      doc.text(`Reg: ${doctor.medicalRegNumber}`, sigX + 30, y, { align: 'center' });
    }

    y += 10;
  });

  // ─── Add footers to all pages ───
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i, totalPages);
  }

  // Save
  const filename = `Prescription_${(patient.name || 'Patient').replace(/\s+/g, '_')}_${now.toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
